[package]
name = "speak_bot"
version = "0.1.0"
edition = "2018"
description = "Rust API for EVE Online's ESI"
readme = "README.md"
homepage = "https://github.com/celeo/speak_bot"
repository = "https://github.com/celeo/speak_bot"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]
keywords = [
  "discord"
]
categories = [
  "command-line-utilities"
]

[dependencies]
anyhow = "1.0.42"
serenity = "0.10.8"
structopt = { version = "0.3.22", default-features = false }
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread"] }
