name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
      - name: Build release
        run: cargo build --release
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/release/speak_bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
